name: Relatório Diário Carteira

on:
  schedule:
    # 11:00 UTC = 08:00 Brasil (aprox)
    - cron: '0 11 * * *'
  workflow_dispatch: # Permite rodar botão manual para testar

jobs:
  enviar-relatorio:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: |
          python -m pip install --upgrade pip
          # Instala apenas o necessário para o relatório
          pip install pandas requests

      - name: Executar Relatório
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
          SHEET_URL_FIIS: ${{ secrets.SHEET_URL_FIIS }} # AQUI ESTÁ O SEGREDO
        run: python daily_report.py